name: "Hello"

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Birji!"
      - name: Give me the date
        run: date
      - name: Buscanda
        run: ls -l